name: Build EXE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install Neutralino CLI
      run: npm install -g @neutralinojs/neu

    - name: Force Download Binaries
      run: neu update

    - name: Build Application
      run: neu build

    - name: Prepare Final Windows Folder
      run: |
        mkdir windows-app
        copy bin\neutralino-win_x64.exe windows-app\Farmasi.exe
        copy dist\resources.neu windows-app\resources.neu
      shell: cmd

    - name: Upload EXE Result
      uses: actions/upload-artifact@v4
      with:
        name: Aplikasi-Farmasi-Windows
        path: windows-app/
